[programs.devnet]
myepicproject = "G141S7RtHKZpvQwdZNfNHVWDDAtBUVKzLwddDS2u42tL"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/kojusola/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js" 

[test]
startup_wait = 100000
